# Site
repository: neilgerring/neilgerring.github.io
favicon: images/favicon.ico

# Personal info
name: Neil Gerring
title: Full Stack Software Developer
email: ng@neilgerring.co.uk
website: www.neilgerring.co.uk

# Social links
github_username: neilgerring
linkedin_username: neil-gerring
# About Section
# about_title: About Me
about_profile_image: images/me.JPG

about_content: |
  Hi, my name is Neil Gerring, I'm a Full Stack Software Developer with over 5 years experience, based in Oxfordshire.
  I am currently working as a Software Developer for Osirium on their task automation platform, PPA.

  I enjoy developing a range of software across the stack and taking a feature from design and planning stages to completion.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. The languages and frameworks I currently have the most experience working with are:
  <mark>Python</mark>,
  <mark>Golang</mark>,
  <mark>ReactJS</mark>,
  and <mark>Postgresql</mark>.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme
